---
execute:
  daemon: 3600
  cache: true

julia:
  exeflags: ["--project=@."]


mainfont: Lato
fontsize: 11pt

format:
  pdf:
    documentclass: report
    number-sections: true
    number-depth: 2
    crossref:
      chapters: true
      fig-prefix: "Figure"
      sec-prefix: "Section"
    include-in-header: julia/header.tex
    filters:
      - julia/revision-filter.lua
    monofont: JuliaMono
    monofontoptions: "Scale=0.75"
    papersize: A4

header-includes:
  - \def\companyName{Agilitus Qld}
  - \def\logoCompany{C:/Users/Josua/Juliarepo/agilitex_header/images/logo-agilitus.png}
  - \def\client{Client}
  - \def\logoClient{images/logo-client.png}
  - \def\projNo{25xxx}
  - \def\projTitle{Title}
  - \def\calcNumber{25xxx-ST-CAL-000y}
  - \def\calcTitle{calc title}
  - \def\projPhase{Concept Design}

revisions:
  - revNo:
    revDate:
    revDesc:
    revAuthor:
    revCheck:
    revApp:
  - revNo: A
    revDate: 15/01/25
    revDesc: IFIR
    revAuthor: Josua A.
    revCheck: x.y.
    revApp:
---

```{=latex}
\coverpageHeader{Calculation Objective / Scope}
```
* Design slab foundation common to both donkey boiler and stack
* Design slab foundation common to both donkey boiler and stack


```{=latex}
\coverpageHeader{Calculation Assumptions}
```
- Soil spring based on 150kPa/20mm stiffness

```{=latex}
\coverpageHeader{Software Used}
```
* RFEM

```{=latex}
\coverpageHeader{Holds}
```

* n/a

<!-- reset the margins  -->
```{=latex}
\newgeometry{
    a4paper,
    top=15mm,
    bottom=15mm ,
    left=15mm,
    right=15mm,
    includeheadfoot
}
\afterpage{\restoregeometry}
```

{{< pagebreak >}}

<!-- add TOC using latex -->
```{=latex}
\tableofcontents
```

{{< pagebreak >}}


# Introduction {#sec-intro}

## Calculation Objective / Scope

The existing boiler is to be removed by lifting it and inserting a skate
so it can be rolled out.

This calculation presents the FEA of the jacking plates added to the
boiler frame, and design of piping supports

## Exclusions

This calculation excludes the following: - design of rollers and
supporting mechanisms

## Basis of Design

In general, design is in accordance with AS 4100 for steel.

## Design Standards and Codes

Unless specifically noted, the design complies with Australian Standards
and selected international standards as listed in the Design Criteria.
The following summarizes the key standards used in producing this
calculation:

-   AS 1170.0 - 2002 Structural design actions - Part 0: General
    principles
-   AS 1170.1 - 2002 Structural design actions - Part 1: Permanent,
    imposed and other actions
-   AS 1170.2 - 2021 Structural design actions - Part 2: Wind actions
-   AS 3600 - 2018 Concrete structures
-   AS 4100 - 1998 Steel structures

## Other Reference Documents

Other reference documents used in this design include:

-   3D laser scan data

{{< pagebreak >}}

# Assumptions

## Holds

-   n/a

## Assumptions {#sec-assumptions}

-   Differential displacement between adjacent jacking point is must be < L/600
-   centerline of jack is no more than 195mm from edge of bottom frame

## Relied on Information

-   3D scan, site photos

{{< pagebreak >}}

# Methodology

-   Perform member check using Space Gass model, to get sanity check of the member capacity, design load ratio must be less than 1.0
-   Perform FEA of the jacking point and check for limiting stresses and strains, where applicable. Acceptance criteria as follows
    - design stress < 0.9Fy, for regions away from geometric discontinuities.
    - plastic equivalent strain (VM strains) < 5%


```{julia}
#| label: activate
#| echo: false
#| output: false
using Pkg
Pkg.activate(".")
# PackageSpec(path=raw"C:\\Users\\Josua\\Juliarepo\\MyUnits/")
```

```{julia}
#| label: using
#| echo: false
#| output: false
using Unitful, DataFrames, XLSX, Plots, Unitful.DefaultSymbols, Revise
using MyUnits, MyHelper, WindLoadModule, SeismicLoadModule, FootingModule, ConcreteModule
```

# RFEM MODEL OF JACKING PLATES

```{julia}
5m + 6m
```

```{julia}
5kN + 6kN
```

## Load - Self weight

{{< pagebreak >}}

## Pretty Tables

Following table summarises the connection loads and capacities:

```{julia}
#| echo: false
#| output: false
dfConn = DataFrame(
    Name=[c.name for c in vConn],
    RL=[c.rl_location for c in vConn],
    Axial_kN=[ustrip(u"kN", c.load_axial) for c in vConn],
    Axial_cap=[ustrip(u"kN", c.cap_axial) for c in vConn],
    Shear_kN=[ustrip(u"kN", c.load_shear) for c in vConn],
    Shear_cap=[ustrip(u"kN", c.cap_shear) for c in vConn],
    Moment_kNm=[ustrip(u"kN*m", c.load_moment) for c in vConn],
    Moment_cap=[ustrip(u"kN*m", c.cap_moment) for c in vConn],
    utilisation=[1 / c.cap_factor |> f2 for c in vConn])
```


```{julia}
#| echo: false
#| output: asis
#|
header = [["Connection", "Location", MultiColumn(2, "P (kN)"), MultiColumn(2, "V (kN)"), MultiColumn(2, "M (kNm)"), "Utilisation"],
    [" ", "", "load", "capacity", "load", "capacity", "load", "capacity", " "]]
pretty_table(
    dfConn;
    column_labels=header,
    backend=:latex
)
```

## Chem anchor/base plate design

```{=latex}
\includepdf[pages=-, fitpaper=true, rotateoversize=true]{pdf-to-embed/chemset.pdf}
```


 ```{=latex }
\appendixHeader{Appendix A  \\ Preliminary Pump Information}
\addcontentsline{toc}{section}{Appendix A - Preliminary Pump Information}
 ```
